\c :mosipdbname

GRANT CONNECT
   ON DATABASE :mosipdbname
   TO audituser;

GRANT USAGE
   ON SCHEMA audit
   TO :dbuname;

GRANT SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES
      ON ALL TABLES IN SCHEMA audit
          TO :dbuname;

ALTER DEFAULT PRIVILEGES IN SCHEMA audit
	GRANT SELECT,INSERT,UPDATE,DELETE,REFERENCES ON TABLES TO :dbuname;
