\c :mosipdbname

REASSIGN OWNED BY sysadmin TO postgres;

REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA audit FROM :dbuname;

REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA audit FROM sysadmin;

GRANT SELECT, INSERT, TRUNCATE, REFERENCES, UPDATE, DELETE ON ALL TABLES IN SCHEMA audit TO :dbuname;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA audit TO postgres;
ALTER TABLE audit.app_audit_log ALTER COLUMN host_ip TYPE varchar(256) USING host_ip::varchar;